export const events = [
  {
    id: "1",
    title: "Urban Photography Workshop",
    description:
      "Learn street photography techniques from a professional photographer.",
    date: "Wed, Dec 31, 2025 • 14:00",
    location: "New York, NY",
    capacity: 30,
    booked: 18,
    price: 0,
    category: "Workshop",
    isFree: true,
    imageUrl: "/images/events/urban-photography-workshop.png",
  },
  {
    id: "2",
    title: "Jazz Night Live",
    description:
      "Enjoy an evening of live jazz performances at the downtown lounge.",
    date: "Mon, Jan 06, 2026 • 19:00",
    location: "Chicago, IL",
    capacity: 50,
    booked: 42,
    price: 25,
    category: "Music",
    isFree: true,
    imageUrl: "/images/events/jazz-night-live.png",
  },
  {
    id: "3",
    title: "Coding Bootcamp: Intro to Python",
    description: "Hands-on Python workshop designed for complete beginners.",
    date: "Sat, Jan 10, 2026 • 10:00",
    location: "Online",
    capacity: 100,
    booked: 76,
    price: 0,
    category: "Tech",
    isFree: true,
    imageUrl: "/images/events/coding-bootcamp-intro-to-python.png",
  },
  {
    id: "4",
    title: "Mindfulness & Meditation Retreat",
    description:
      "A half-day retreat focused on mindfulness techniques and relaxation.",
    date: "Thu, Jan 22, 2026 • 09:00",
    location: "San Francisco, CA",
    capacity: 40,
    booked: 29,
    price: 40,
    category: "Wellness",
    isFree: true,
    imageUrl: "/images/events/mindfulness-and-meditation-retreat.png",
  },
  {
    id: "5",
    title: "Local Food Festival",
    description:
      "Taste local delicacies and enjoy live music at the city park.",
    date: "Sun, Feb 02, 2026 • 12:00",
    location: "Austin, TX",
    capacity: 200,
    booked: 134,
    price: 0,
    category: "Festival",
    isFree: true,
    imageUrl: "/images/events/local-food-festival.png",
  },
  {
    id: "6",
    title: "Art & Wine Evening",
    description: "An evening of painting and wine tasting with local artists.",
    date: "Fri, Feb 14, 2026 • 18:00",
    location: "Los Angeles, CA",
    capacity: 60,
    booked: 47,
    price: 35,
    category: "Art",
    isFree: true,
    imageUrl: "/images/events/art-and-wine-evening.png",
  },
];
